package com.recoverx.datagen;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.recoverx.domain.FailedTransaction;
import com.recoverx.domain.FailureReason;

import java.io.BufferedWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * Writes the batch to disk as four artifacts:
 *
 * <ul>
 *   <li>failed_transactions.jsonl - the only file the agent may read</li>
 *   <li>ground_truth.jsonl - recoverability truth, eval harness only</li>
 *   <li>failed_transactions.csv - same agent view, for eyeballing in a spreadsheet</li>
 *   <li>DATASET.md - the mix, the ceiling, and the seed, so a reviewer can reproduce it</li>
 * </ul>
 *
 * Keeping the truth in a separate file is not cosmetic. It is the thing that lets
 * you claim the agent never saw the answer, and a judge can verify that claim by
 * grepping the agent's code for the filename.
 */
public class DatasetWriter {

    private final ObjectMapper mapper = new ObjectMapper()
            .registerModule(new JavaTimeModule())
            .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS);

    public void write(List<FailedTransaction> batch, GeneratorConfig config) throws IOException {
        Files.createDirectories(config.outDir());

        writeJsonl(config.outDir().resolve("failed_transactions.jsonl"),
                batch.stream().map(FailedTransaction::redacted).toList());
        writeJsonl(config.outDir().resolve("ground_truth.jsonl"),
                batch.stream().map(FailedTransaction::groundTruth).toList());
        writeCsv(config.outDir().resolve("failed_transactions.csv"), batch);
        writeSummary(config.outDir().resolve("DATASET.md"), batch, config);
    }

    private void writeJsonl(Path path, List<?> rows) throws IOException {
        try (BufferedWriter writer = Files.newBufferedWriter(path, StandardCharsets.UTF_8)) {
            for (Object row : rows) {
                writer.write(mapper.writeValueAsString(row));
                writer.newLine();
            }
        }
    }

    private void writeCsv(Path path, List<FailedTransaction> batch) throws IOException {
        try (BufferedWriter writer = Files.newBufferedWriter(path, StandardCharsets.UTF_8)) {
            writer.write("txn_id,order_id,amount_inr,method,failed_at,error_code,acquirer,"
                    + "customer_id,payday_day,prior_failures_30d,has_saved_card,raw_gateway_error");
            writer.newLine();
            for (FailedTransaction txn : batch) {
                writer.write(String.join(",",
                        txn.txnId(),
                        txn.orderId(),
                        rupees(txn.amountPaise()),
                        txn.method().name(),
                        txn.failedAt().toString(),
                        txn.errorCode(),
                        txn.acquirer(),
                        txn.customer().customerId(),
                        String.valueOf(txn.customer().paydayDayOfMonth()),
                        String.valueOf(txn.customer().priorFailures30d()),
                        String.valueOf(txn.customer().hasSavedCard()),
                        csvQuote(txn.rawGatewayError())));
                writer.newLine();
            }
        }
    }

    private void writeSummary(Path path, List<FailedTransaction> batch, GeneratorConfig config)
            throws IOException {

        long totalPaise = batch.stream().mapToLong(FailedTransaction::amountPaise).sum();
        long recoverablePaise = batch.stream()
                .filter(t -> t.truth().recoverable())
                .mapToLong(FailedTransaction::amountPaise).sum();
        long trapCount = batch.stream().filter(t -> t.truth().mustNotRetry()).count();
        long novelCount = batch.stream().filter(FailedTransaction::novelErrorForm).count();
        long trapPaise = batch.stream()
                .filter(t -> t.truth().mustNotRetry())
                .mapToLong(FailedTransaction::amountPaise).sum();

        Map<FailureReason, long[]> byReason = new LinkedHashMap<>();
        for (FailureReason reason : GeneratorConfig.failureMix().keySet()) {
            byReason.put(reason, new long[]{0, 0, 0});
        }
        for (FailedTransaction txn : batch) {
            long[] row = byReason.get(txn.trueReason());
            row[0]++;
            row[1] += txn.amountPaise();
            if (txn.truth().recoverable()) {
                row[2] += txn.amountPaise();
            }
        }

        StringBuilder sb = new StringBuilder();
        sb.append("# Dataset card\n\n")
                .append("Generated by `SyntheticDataGenerator`. Fully reproducible from the seed.\n\n")
                .append("| Parameter | Value |\n|---|---|\n")
                .append("| Transactions | ").append(batch.size()).append(" |\n")
                .append("| Seed | ").append(config.seed()).append(" |\n")
                .append("| Window | last ").append(config.window().toDays()).append(" days |\n")
                .append("| Merchant | `").append(config.merchantId()).append("` |\n\n")
                .append("## Money at stake\n\n")
                .append("| Metric | Amount |\n|---|---|\n")
                .append("| Total failed value | Rs ").append(rupees(totalPaise)).append(" |\n")
                .append("| Recoverable ceiling (oracle) | Rs ").append(rupees(recoverablePaise))
                .append(" (").append(pct(recoverablePaise, totalPaise)).append(") |\n")
                .append("| Permanently lost | Rs ").append(rupees(totalPaise - recoverablePaise))
                .append(" |\n\n")
                .append("No agent can beat the oracle ceiling. Report recovered rupees as a\n")
                .append("fraction of it, never as a fraction of total failed value.\n\n")
                .append("## Do-not-retry trap\n\n")
                .append(trapCount).append(" transactions (Rs ").append(rupees(trapPaise))
                .append(") are flagged `mustNotRetry`. They are risk-blocked. Retrying one is\n")
                .append("a compliance violation and must be counted separately from a wasted\n")
                .append("attempt - report it as its own metric, not folded into precision.\n\n")
                .append("## Unseen error wordings\n\n")
                .append(novelCount).append(" of ").append(batch.size())
                .append(" rows use a gateway wording no rule was written for - other vendors,\n")
                .append("raw ISO 8583, regional phrasing. `RuleBasedClassifier` was written against the\n")
                .append("documented forms only, so this slice is where a language model has to earn\n")
                .append("its cost. The classification report scores every arm on both slices separately.\n\n")
                .append("## Failure mix\n\n")
                .append("| Reason | Count | Value | Recoverable value |\n|---|---:|---:|---:|\n");

        byReason.forEach((reason, row) -> sb.append("| ").append(reason).append(" | ")
                .append(row[0]).append(" | Rs ").append(rupees(row[1]))
                .append(" | Rs ").append(rupees(row[2])).append(" |\n"));

        sb.append("\n## Files\n\n")
                .append("| File | Who may read it |\n|---|---|\n")
                .append("| `failed_transactions.jsonl` | the agent |\n")
                .append("| `failed_transactions.csv` | humans |\n")
                .append("| `ground_truth.jsonl` | the eval harness only |\n")
                .append("| `DATASET.md` | this file |\n");

        Files.writeString(path, sb.toString(), StandardCharsets.UTF_8);
    }

    private static String rupees(long paise) {
        return String.format("%.2f", paise / 100.0);
    }

    private static String pct(long part, long whole) {
        return whole == 0 ? "0.0%" : String.format("%.1f%%", 100.0 * part / whole);
    }

    private static String csvQuote(String value) {
        return "\"" + value.replace("\"", "\"\"") + "\"";
    }
}
